site_name: "Team Brewtal Coders Submission"

docs_dir: .


theme:
  name: material
  features:
    - navigation.instant
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    # Dark mode (default)
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Light mode
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: "Roboto"
    code: "Roboto Mono"

nav:
  - Home: README.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - meta
  - def_list
  - abbr
  - tables
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.smartsymbols

plugins:
  - search